services:
  db:
    container_name: komflow-postgres-db
    image: postgres
    restart: always
    ports:
      - 5432:5433
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

  adminer:
    container_name: komflow-adminer-pg
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8091:8080

#  flyway:
#    image: boxfuse/flyway
#    command: -url=jdbc:postgresql:8091/spring-mastering -schemas=public -user=root -password=root migrate
#    volumes:
#      - ./flyway:/flyway/sql
#    depends_on:
#      - db